"""test running migrations

Revision ID: 309a4c847ae6
Revises: 728ada1a2c79
Create Date: 2023-02-01 18:14:00.370625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309a4c847ae6'
down_revision = '728ada1a2c79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
