"""test running migrations

Revision ID: 440e11de3a35
Revises: d342bb29e809
Create Date: 2023-02-01 18:09:03.993080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440e11de3a35'
down_revision = 'd342bb29e809'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
