"""test running migrations

Revision ID: 594fbcb0ebd1
Revises: 309a4c847ae6
Create Date: 2023-02-01 18:14:24.019764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594fbcb0ebd1'
down_revision = '309a4c847ae6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
