"""test running migrations

Revision ID: 6b208d9ee03c
Revises: 8331f4b3bc9d
Create Date: 2023-02-01 18:10:07.588809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b208d9ee03c'
down_revision = '8331f4b3bc9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
