"""test running migrations

Revision ID: 728ada1a2c79
Revises: 947c762a300e
Create Date: 2023-02-01 18:12:29.327143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728ada1a2c79'
down_revision = '947c762a300e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
