"""test running migrations

Revision ID: 8099dee4c018
Revises: 1af001d5be43
Create Date: 2023-03-02 14:43:03.348763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8099dee4c018'
down_revision = '1af001d5be43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
