"""test running migrations

Revision ID: 8331f4b3bc9d
Revises: 440e11de3a35
Create Date: 2023-02-01 18:09:25.621079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8331f4b3bc9d'
down_revision = '440e11de3a35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
