"""test running migrations

Revision ID: 947c762a300e
Revises: 6b208d9ee03c
Create Date: 2023-02-01 18:11:06.963281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947c762a300e'
down_revision = '6b208d9ee03c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
