"""test running migrations

Revision ID: 4ef0546045ea
Revises: 9f0fc05aed12
Create Date: 2023-03-02 14:28:22.301336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef0546045ea'
down_revision = '9f0fc05aed12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
