"""test running migrations

Revision ID: 51c4888fb391
Revises: 815b4505c634
Create Date: 2023-03-02 14:39:12.047530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c4888fb391'
down_revision = '815b4505c634'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
