"""test running migrations

Revision ID: 80a5341fd50c
Revises: c57c2eaff83a
Create Date: 2023-03-02 14:26:53.228811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a5341fd50c'
down_revision = 'c57c2eaff83a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
