"""test running migrations

Revision ID: 815b4505c634
Revises: 4ef0546045ea
Create Date: 2023-03-02 14:29:01.287399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815b4505c634'
down_revision = '4ef0546045ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
