"""test running migrations

Revision ID: 8b2ff7a3e431
Revises: b9ededdc731e
Create Date: 2023-03-02 14:25:59.548800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2ff7a3e431'
down_revision = 'b9ededdc731e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
