"""test running migrations

Revision ID: b716e3cf3f68
Revises: e65394e4dbea
Create Date: 2023-03-02 14:23:28.350485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b716e3cf3f68'
down_revision = 'e65394e4dbea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
