"""test running migrations

Revision ID: c57c2eaff83a
Revises: 8b2ff7a3e431
Create Date: 2023-03-02 14:26:12.748658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57c2eaff83a'
down_revision = '8b2ff7a3e431'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
