"""test running migrations

Revision ID: d0d5fb0d0506
Revises: 80a5341fd50c
Create Date: 2023-03-02 14:27:10.736767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d5fb0d0506'
down_revision = '80a5341fd50c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
