"""test running migrations

Revision ID: f43bd16cca4c
Revises: 51c4888fb391
Create Date: 2023-03-02 14:40:40.525114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43bd16cca4c'
down_revision = '51c4888fb391'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
